### ISSUE TITLE
Help for MMD code (not related to libMMD)

### ISSUE THREAD

**Issue by LauraKami** [AiMiDi/libMMD#18]
Hello,
I saw in your repositories that you know MMD well.
I'm trying to compile MMD plugins, and I'm looking for MMDexport.lib, I have the header, but it's impossible to find this library needed for the link. 
As you have developed a tool for MMD, perhaps you have this library or a link to find it.
Any documentation on MMD export and plugins are welcome.
Thank you in advance, Happy New Year.
Thank's Laura
Ref and link to MikuMikuDance chinese edition are welcome, I'v developped an Miku Installer , ( for young french), but now I will upgrade to other language.
https://mikumikudance.fr

**Comment by AiMiDi** [comment]
You can find the required library files and header files in the Data folder of the MMD software installation directory:
![image](https://github.com/AiMiDi/libMMD/assets/76622021/4e674edd-35e2-4de9-96f1-3f660dfaee2e)

I recommend referring to [mmdbridge](https://github.com/uimac/mmdbridge/tree/master) it is a relatively complete plugin, including how to set the window and so on.

**Comment by AiMiDi** [comment]
Or you can just use my 926 version of data
[MikuMikuDancebridge 926 Data.zip](https://github.com/AiMiDi/libMMD/files/13855962/MikuMikuDancebridge.926.Data.zip)

**Comment by LauraKami** [comment]
Thank you so much.
In the English version we don't have these MMDexport files like in your capture.
In Europe (and the USA?) we can no longer access Yu Higuchi's site.
https://www.geocities.jp/higuchuu4/index.htm, it is reserved only for Japanese…
Saw MMBridge, but it doesn't have the MMDexport.lib file ;o)
But, I should have searched with bing instead of google...

In any case thank you very much, have a great new year
